# Generated by Django 3.2.14 on 2022-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('short', models.TextField(blank=True, null=True)),
                ('in_calendar', models.BooleanField(default=False)),
                ('date_of', models.DateTimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
