# Generated by Django 3.2.14 on 2022-07-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-created', '-id']},
        ),
    ]
