# Generated by Django 3.2.14 on 2022-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('created', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
