# Generated by Django 3.2.14 on 2022-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
