# Generated by Django 3.2.14 on 2022-07-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20220730_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-created']},
        ),
    ]
