# Generated by Django 3.2.14 on 2022-10-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_information_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='body',
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.information')),
            ],
        ),
    ]
